name: hero
channels:
  - pytorch
dependencies:
  - pip:
    - horovod==0.18.2
    - ipdb==0.12
    - lmdb==0.97
    - lz4==2.1.9
    - tensorboardX==1.7
    - transformers==2.0.0
  - cudatoolkit=10.1.243
  - cudnn=7.6.4
  - pip=21
  - python=3.6
  - pytorch=1.3.0
  - torchvision=0.4.1
variables:
  HOROVOD_GPU_ALLREDUCE: NCCL
  HOROVOD_NCCL_LINK: SHARED
  HOROVOD_WITH_PYTORCH: 1
